<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
  </PropertyGroup>
  <!--Package versions-->
  <PropertyGroup>
    <VmrFoof8166516PackageVersion>1.2.1</VmrFoof8166516PackageVersion>
    <VmrBarf8166516PackageVersion>2.2.1</VmrBarf8166516PackageVersion>
    <VmrBazf8166516PackageVersion>3.1.0</VmrBazf8166516PackageVersion>
  </PropertyGroup>
</Project>
