<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
  </PropertyGroup>
  <!--Package versions-->
  <PropertyGroup>
    <VmrFooab9584e2PackageVersion>1.2.1</VmrFooab9584e2PackageVersion>
    <VmrBarab9584e2PackageVersion>2.2.1</VmrBarab9584e2PackageVersion>
    <VmrBazab9584e2PackageVersion>3.1.0</VmrBazab9584e2PackageVersion>
  </PropertyGroup>
</Project>
