<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
  </PropertyGroup>
  <!--Package versions-->
  <PropertyGroup>
    <VmrFooc7767a8dPackageVersion>1.2.1</VmrFooc7767a8dPackageVersion>
    <VmrBarc7767a8dPackageVersion>2.2.1</VmrBarc7767a8dPackageVersion>
    <VmrBazc7767a8dPackageVersion>3.1.0</VmrBazc7767a8dPackageVersion>
  </PropertyGroup>
</Project>
