<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
  </PropertyGroup>
  <!--Package versions-->
  <PropertyGroup>
    <VmrBar49d4f030PackageVersion>2.1.0</VmrBar49d4f030PackageVersion>
    <VmrBaz49d4f030PackageVersion>3.1.0</VmrBaz49d4f030PackageVersion>
  </PropertyGroup>
</Project>
