<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
  </PropertyGroup>
  <!--Package versions-->
  <PropertyGroup>
    <VmrBare67b38e0PackageVersion>2.1.1</VmrBare67b38e0PackageVersion>
    <VmrBaze67b38e0PackageVersion>3.1.0</VmrBaze67b38e0PackageVersion>
  </PropertyGroup>
</Project>
